python -m torch.distributed.launch \
  --nproc_per_node=8 main_dino.py \
  --arch vit_small \
  --num_workers 50 \
  --data_path data/mini_imagenet/train/ \
  --output_dir ./$experiment \
  --norm_last_layer False \
  --use_fp16 False \
  --clip_grad 0 \
  --epochs 800 \
  --global_crops_scale 0.25 1.0 \
  --local_crops_number 10 \
  --local_crops_scale 0.05 0.25 \
  --teacher_temp 0.07 \
  --warmup_teacher_temp_epochs 30 \
  --clip_grad 0 \
  --min_lr 0.00001  2>&1 | tee $experiment.log